default_chain: stride-testnet
chains:
  gaia-testnet:
    key: walltstride
    chain-id: GAIA
    rpc-addr: http://46.101.50.135:23657       # Gaia RPC yazacağız
    grpc-addr: http://46.101.50.135:23090      # Gaia GRPC yazacağız
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: cüzdanisminiz
    chain-id: STRIDE-TESTNET-4
    rpc-addr:  http://127.0.0.1:16657      # Stride RPC yazacağız
    grpc-addr: http://0.0.0.0:16090        # Stride GRPC yazacağıze
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
